### ISSUE TITLE
Platform maintenance and improvements. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1350]
**Briefly describe the Initiative.**
Quality of life improvements around the platform. Bug fixes, updates and upgrades and improvements that will benefit User Experience.

**What is the requested timeline for completion?**
End of Q4 2023

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/sumo/issues/547
- [ ] https://github.com/mozilla/sumo/issues/1249
- [ ] https://github.com/mozilla/sumo/issues/1235
- [ ] https://github.com/mozilla/sumo/issues/1221
- [ ] https://github.com/mozilla/sumo/issues/1233
- [ ] https://github.com/mozilla/sumo/issues/1340
- [ ] https://github.com/mozilla/sumo/issues/1354
- [ ] https://github.com/mozilla/sumo/issues/1251
- [ ] https://github.com/mozilla/sumo/issues/1360
- [ ] https://github.com/mozilla/sumo/issues/1359
- [ ] https://github.com/mozilla/sumo/issues/1183
- [ ] https://github.com/mozilla/sumo/issues/1184
- [ ] https://github.com/mozilla/sumo/issues/1137
- [ ] https://github.com/mozilla/sumo/issues/1013
- [ ] https://github.com/mozilla/sumo/issues/862
- [ ] https://github.com/mozilla/sumo/issues/1434
```
