### ISSUE TITLE
Migrate SuMo to PostgreSQL

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1352]
**Briefly describe the Initiative.**
Migrate from MySQL to PostgreSQL with minimum downtime.

**What is the requested timeline for completion?**
End of Q3

```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/sumo/issues/1366
- [ ] https://github.com/mozilla/sumo/issues/1367
- [ ] https://github.com/mozilla/sumo/issues/1395
- [ ] https://github.com/mozilla/sumo/issues/1396
- [ ] https://github.com/mozilla/sumo/issues/1398
- [ ] https://github.com/mozilla/sumo/issues/1397
- [ ] https://github.com/mozilla/sumo/issues/1420
- [ ] https://github.com/mozilla/sumo/issues/1422
- [ ] https://github.com/mozilla/sumo/issues/1431
- [ ] https://github.com/mozilla/sumo/issues/1430
- [ ] https://github.com/mozilla/sumo/issues/1429
- [ ] https://github.com/mozilla/sumo/issues/1428
- [ ] https://github.com/mozilla/sumo/issues/1426
- [ ] https://github.com/mozilla/sumo/issues/1427
- [ ] https://github.com/mozilla/sumo/issues/1432
- [ ] https://github.com/mozilla/sumo/issues/1437
- [ ] https://github.com/mozilla/sumo/issues/1435
- [ ] https://github.com/mozilla/sumo/issues/1438
- [ ] https://github.com/mozilla/sumo/issues/1440
- [ ] https://github.com/mozilla/sumo/issues/1441
- [ ] https://github.com/mozilla/sumo/issues/1442
- [ ] https://github.com/mozilla/sumo/issues/1443
- [ ] https://github.com/mozilla/sumo/issues/1444
- [ ] https://github.com/mozilla/sumo/issues/1445
- [ ] https://github.com/mozilla/sumo/issues/1446
- [ ] https://github.com/mozilla/sumo/issues/1447
- [ ] https://github.com/mozilla/sumo/issues/1449
- [ ] https://github.com/mozilla/sumo/issues/1485
```
