### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1371]
UI and UX improvements
### Tasks
- [ ] https://github.com/mozilla/sumo/issues/1279
- [ ] https://github.com/mozilla/sumo/issues/1278
- [ ] https://github.com/mozilla/sumo/issues/1255
- [ ] https://github.com/mozilla/sumo/issues/1248
- [ ] https://github.com/mozilla/sumo/issues/1238
- [ ] https://github.com/mozilla/sumo/issues/1228
- [ ] https://github.com/mozilla/sumo/issues/1227
- [ ] https://github.com/mozilla/sumo/issues/1225
- [ ] https://github.com/mozilla/sumo/issues/1214
- [ ] https://github.com/mozilla/sumo/issues/1212
- [ ] https://github.com/mozilla/sumo/issues/1211
- [ ] https://github.com/mozilla/sumo/issues/1208
- [ ] https://github.com/mozilla/sumo/issues/1207
- [ ] https://github.com/mozilla/sumo/issues/1206
- [ ] https://github.com/mozilla/sumo/issues/1205
- [ ] https://github.com/mozilla/sumo/issues/1204
- [ ] https://github.com/mozilla/sumo/issues/1203
- [ ] https://github.com/mozilla/sumo/issues/1202
- [ ] https://github.com/mozilla/sumo/issues/1201
- [ ] https://github.com/mozilla/sumo/issues/1199
- [ ] https://github.com/mozilla/sumo/issues/1197
- [ ] https://github.com/mozilla/sumo/issues/1196
- [ ] https://github.com/mozilla/sumo/issues/1193
- [ ] https://github.com/mozilla/sumo/issues/1176
- [ ] https://github.com/mozilla/sumo/issues/1134
- [ ] https://github.com/mozilla/sumo/issues/1048
- [ ] https://github.com/mozilla/sumo/issues/1111
- [ ] https://github.com/mozilla/sumo/issues/1101
- [ ] https://github.com/mozilla/sumo/issues/1093
- [ ] https://github.com/mozilla/sumo/issues/993
- [ ] https://github.com/mozilla/sumo/issues/968
- [ ] https://github.com/mozilla/sumo/issues/961
- [ ] https://github.com/mozilla/sumo/issues/960
- [ ] https://github.com/mozilla/sumo/issues/942
- [ ] https://github.com/mozilla/sumo/issues/930
- [ ] https://github.com/mozilla/sumo/issues/891
- [ ] https://github.com/mozilla/sumo/issues/1030
- [ ] https://github.com/mozilla/sumo/issues/814
- [ ] https://github.com/mozilla/sumo/issues/812
- [ ] https://github.com/mozilla/sumo/issues/745
- [ ] https://github.com/mozilla/sumo/issues/687
- [ ] https://github.com/mozilla/sumo/issues/632
- [ ] https://github.com/mozilla/sumo/issues/587
- [ ] https://github.com/mozilla/sumo/issues/95
- [ ] https://github.com/mozilla/sumo/issues/77
- [ ] https://github.com/mozilla/sumo/issues/97
- [ ] https://github.com/mozilla/sumo/issues/390
- [ ] https://github.com/mozilla/sumo/issues/281
- [ ] https://github.com/mozilla/sumo/issues/293
- [ ] https://github.com/mozilla/sumo/issues/298
- [ ] https://github.com/mozilla/sumo/issues/348
- [ ] https://github.com/mozilla/sumo/issues/372
- [ ] https://github.com/mozilla/sumo/issues/431
- [ ] https://github.com/mozilla/sumo/issues/439
- [ ] https://github.com/mozilla/sumo/issues/444
- [ ] https://github.com/mozilla/sumo/issues/510
- [ ] https://github.com/mozilla/sumo/issues/516
- [ ] https://github.com/mozilla/sumo/issues/532
- [ ] https://github.com/mozilla/sumo/issues/533
- [ ] https://github.com/mozilla/sumo/issues/546
- [ ] https://github.com/mozilla/sumo/issues/558
- [ ] https://github.com/mozilla/sumo/issues/562
- [ ] https://github.com/mozilla/sumo/issues/1448
- [ ] https://github.com/mozilla/sumo/issues/1451
- [ ] https://github.com/mozilla/sumo/issues/1458
- [ ] https://github.com/mozilla/sumo/issues/1460
- [ ] https://github.com/mozilla/sumo/issues/1461
- [ ] https://github.com/mozilla/sumo/issues/1486
