### ISSUE TITLE
Front-end improvements

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1373]
Anything related to bundling and improving our assets
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/sumo/issues/998
- [ ] https://github.com/mozilla/sumo/issues/975
- [ ] https://github.com/mozilla/sumo/issues/973
- [ ] https://github.com/mozilla/sumo/issues/956
- [ ] https://github.com/mozilla/sumo/issues/903
- [ ] https://github.com/mozilla/sumo/issues/889
- [ ] https://github.com/mozilla/sumo/issues/888
- [ ] https://github.com/mozilla/sumo/issues/773
- [ ] https://github.com/mozilla/sumo/issues/771
- [ ] https://github.com/mozilla/sumo/issues/772
- [ ] https://github.com/mozilla/sumo/issues/726
- [ ] https://github.com/mozilla/sumo/issues/502
```
