### ISSUE TITLE
[Looker Studio] Add ability to filter by product, topic, and locale in the `KB Helpfulness` dashboard

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1835]
Add the ability to filter/sort by an article's product, topic, or locale in the `KB Helpfulness` Looker Studio dashboard.
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/sumo/issues/1844
- [x] Adjust `metrics_kb_votes_details` scheduled query to use the new `kitsune_wiki_document_plus` BQ table so it can pull in its extra fields
- [x] Add product, topic, and locale filters to the appropriate pages within the `KB Helpfulness` Looker Studio dashboard
```
